# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Layout.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import (
    QHBoxLayout,
    QLabel,
    QScrollArea,
    QSplitter,
    QWidget,
    QVBoxLayout,
)

from labelvim.widgets.canvas_widget import CanvasWidget
from labelvim.widgets.list_widgets import (
    CustomLabelWidget,
    CustomListViewWidget,
    CustomObjectListWidget,
)


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1850, 873)
        MainWindow.setMinimumSize(1000, 400)
        icon = QtGui.QIcon()
        icon.addPixmap(
            QtGui.QPixmap("labelvim/icon/Logo.jpeg"), QtGui.QIcon.Normal, QtGui.QIcon.Off
        )
        MainWindow.setWindowIcon(icon)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setAnimated(True)

        self.centralwidget = QtWidgets.QWidget()
        self.centralwidget.setObjectName("centralwidget")
        MainWindow.setCentralWidget(self.centralwidget)

        self.main_hbox = QHBoxLayout(self.centralwidget)
        self.main_hbox.setSpacing(0)
        self.main_hbox.setContentsMargins(0, 0, 0, 0)

        # Custom Widgets
        self.splitter = QSplitter(self.centralwidget)
        self.main_hbox.addWidget(self.splitter)

        self.leftWidget = QWidget()
        self.leftVBox = QVBoxLayout(self.leftWidget)
        self.leftVBox.setSpacing(3)
        self.splitter.addWidget(self.leftWidget)

        self.middleWidget = QWidget()
        self.middleWidget.setMinimumWidth(800)
        self.middleLayout = QVBoxLayout(self.middleWidget)
        self.middleLayout.setContentsMargins(0, 0, 0, 0)
        self.scroll_area = QScrollArea(self.middleWidget)
        self.scroll_area.setWidgetResizable(True)
        self.scroll_area.setAlignment(QtCore.Qt.AlignCenter)
        self.scroll_area.setFrameShape(QtWidgets.QFrame.Box | QtWidgets.QFrame.Plain)
        self.scroll_area.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.canvas_widget = CanvasWidget()
        self.scroll_area.setWidget(self.canvas_widget)
        self.middleLayout.addWidget(self.scroll_area)
        self.splitter.addWidget(self.middleWidget)

        self.rightWidget = QWidget()
        self.rightVBox = QVBoxLayout(self.rightWidget)
        self.rightVBox.setSpacing(2)
        self.splitter.addWidget(self.rightWidget)

        self.splitter.setSizes(
            [100, 1000, 200]
        )  # Left: 100px, Middle: 1000px, Right: 200px
        self.splitter.setStretchFactor(
            1, 1
        )  # Middle widget stretches to take available space

        icon1 = QtGui.QIcon()
        icon1.addPixmap(
            QtGui.QPixmap("labelvim/icon/Open.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off
        )
        self.OpenDirBtn = QtWidgets.QPushButton(self.centralwidget)
        self.OpenDirBtn.setText("")
        self.OpenDirBtn.setIcon(icon1)
        self.OpenDirBtn.setIconSize(QtCore.QSize(50, 50))
        self.OpenDirBtn.setObjectName("OpenDirBtn")
        self.leftVBox.addWidget(self.OpenDirBtn)
        self.SaveDirBtn = QtWidgets.QPushButton()
        self.SaveDirBtn.setText("")
        self.SaveDirBtn.setIcon(icon1)
        self.SaveDirBtn.setIconSize(QtCore.QSize(50, 50))
        self.SaveDirBtn.setObjectName("SaveDirBtn")
        self.leftVBox.addWidget(self.SaveDirBtn)
        self.NextBtn = QtWidgets.QPushButton(self.centralwidget)
        self.NextBtn.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(
            QtGui.QPixmap("labelvim/icon/next.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off
        )
        self.NextBtn.setIcon(icon2)
        self.NextBtn.setIconSize(QtCore.QSize(50, 50))
        self.NextBtn.setObjectName("NextBtn")
        self.leftVBox.addWidget(self.NextBtn)
        self.PreviousBtn = QtWidgets.QPushButton(self.centralwidget)
        self.PreviousBtn.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(
            QtGui.QPixmap("labelvim/icon/prev.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off
        )
        self.PreviousBtn.setIcon(icon3)
        self.PreviousBtn.setIconSize(QtCore.QSize(50, 50))
        self.PreviousBtn.setObjectName("PreviousBtn")
        self.leftVBox.addWidget(self.PreviousBtn)
        self.DeleteFileBtn = QtWidgets.QPushButton(self.centralwidget)
        self.DeleteFileBtn.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(
            QtGui.QPixmap("labelvim/icon/delete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off
        )
        self.DeleteFileBtn.setIcon(icon4)
        self.DeleteFileBtn.setIconSize(QtCore.QSize(50, 50))
        self.DeleteFileBtn.setObjectName("DeleteFileBtn")
        self.leftVBox.addWidget(self.DeleteFileBtn)
        self.CreateObjectBtn = QtWidgets.QPushButton(self.centralwidget)
        self.CreateObjectBtn.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(
            QtGui.QPixmap("labelvim/icon/objects.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off
        )
        self.CreateObjectBtn.setIcon(icon5)
        self.CreateObjectBtn.setIconSize(QtCore.QSize(50, 50))
        self.CreateObjectBtn.setObjectName("CreateObjectBtn")
        self.leftVBox.addWidget(self.CreateObjectBtn)
        self.EditObjectBtn = QtWidgets.QPushButton(self.centralwidget)
        self.EditObjectBtn.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(
            QtGui.QPixmap("labelvim/icon/edit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off
        )
        self.EditObjectBtn.setIcon(icon6)
        self.EditObjectBtn.setIconSize(QtCore.QSize(50, 50))
        self.EditObjectBtn.setObjectName("EditObjectBtn")
        self.leftVBox.addWidget(self.EditObjectBtn)
        self.DeleteAnnotationBtn = QtWidgets.QPushButton(self.centralwidget)
        self.DeleteAnnotationBtn.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(
            QtGui.QPixmap("labelvim/icon/cancel.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off
        )
        self.DeleteAnnotationBtn.setIcon(icon7)
        self.DeleteAnnotationBtn.setIconSize(QtCore.QSize(50, 50))
        self.DeleteAnnotationBtn.setObjectName("DeleteAnnotationBtn")
        self.leftVBox.addWidget(self.DeleteAnnotationBtn)
        self.ClearAnnotationBtn = QtWidgets.QPushButton(self.centralwidget)
        self.ClearAnnotationBtn.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(
            QtGui.QPixmap("labelvim/icon/clear-2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off
        )
        self.ClearAnnotationBtn.setIcon(icon8)
        self.ClearAnnotationBtn.setIconSize(QtCore.QSize(50, 50))
        self.ClearAnnotationBtn.setObjectName("ClearAnnotationBtn")
        self.leftVBox.addWidget(self.ClearAnnotationBtn)
        self.ZoomInBtn = QtWidgets.QPushButton(self.centralwidget)
        self.ZoomInBtn.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(
            QtGui.QPixmap("labelvim/icon/zoom-in.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off
        )
        self.ZoomInBtn.setIcon(icon9)
        self.ZoomInBtn.setIconSize(QtCore.QSize(50, 50))
        self.ZoomInBtn.setObjectName("ZoomInBtn")
        self.leftVBox.addWidget(self.ZoomInBtn)
        self.ZoomOutBtn = QtWidgets.QPushButton(self.centralwidget)
        self.ZoomOutBtn.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(
            QtGui.QPixmap("labelvim/icon/zoom-out.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off
        )
        self.ZoomOutBtn.setIcon(icon10)
        self.ZoomOutBtn.setIconSize(QtCore.QSize(50, 50))
        self.ZoomOutBtn.setObjectName("ZoomOutBtn")
        self.leftVBox.addWidget(self.ZoomOutBtn)
        self.ZoomFitBtn = QtWidgets.QPushButton(self.centralwidget)
        self.ZoomFitBtn.setText("")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(
            QtGui.QPixmap("labelvim/icon/fit-window.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off
        )
        self.ZoomFitBtn.setIcon(icon11)
        self.ZoomFitBtn.setIconSize(QtCore.QSize(50, 50))
        self.ZoomFitBtn.setObjectName("ZoomFitBtn")
        self.leftVBox.addWidget(self.ZoomFitBtn)
        self.ZoomLabel = QtWidgets.QLabel(self.centralwidget)
        # self.ZoomLabel.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.ZoomLabel.autoFillBackground = True
        self.ZoomLabel.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.ZoomLabel.setText("")
        self.ZoomLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.ZoomLabel.setObjectName("ZoomLabel")
        self.leftVBox.addWidget(self.ZoomLabel)
        self.SaveBtn = QtWidgets.QPushButton(self.centralwidget)
        self.SaveBtn.setText("")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(
            QtGui.QPixmap("labelvim/icon/save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off
        )
        self.SaveBtn.setIcon(icon12)
        self.SaveBtn.setIconSize(QtCore.QSize(50, 50))
        self.SaveBtn.setObjectName("SaveBtn")
        self.leftVBox.addWidget(self.SaveBtn)
        # self.label_5 = QtWidgets.QLabel(self.centralwidget)
        # self.label_5.setAutoFillBackground(True)
        # self.label_5.setText("")
        # self.label_5.setObjectName("label_5")
        self.labelLabels = QtWidgets.QLabel(self.centralwidget)
        self.rightVBox.addWidget(self.labelLabels)
        self.LabelWidget = CustomLabelWidget()
        self.rightVBox.addWidget(self.LabelWidget)
        self.LabelWidget.setObjectName("LabelWidget")
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelLabels.setFont(font)
        self.labelLabels.setIndent(5)
        self.labelLabels.setObjectName("label_6")
        self.labelObjectList = QtWidgets.QLabel()
        self.rightVBox.addWidget(self.labelObjectList)
        self.ObjectLabelListWidget = CustomObjectListWidget()
        self.rightVBox.addWidget(self.ObjectLabelListWidget)
        self.ObjectLabelListWidget.setObjectName("ObjectLabelListWidget")
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelObjectList.setFont(font)
        self.labelObjectList.setIndent(5)
        self.labelObjectList.setObjectName("label_7")
        self.labelFileList = QtWidgets.QLabel()
        self.rightVBox.addWidget(self.labelFileList)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelFileList.setFont(font)
        self.labelFileList.setIndent(5)
        self.labelFileList.setObjectName("label_8")

        self.FileListWidget = CustomListViewWidget()
        self.rightVBox.addWidget(self.FileListWidget)
        self.FileListWidget.setObjectName("FileListWidget")

        MainWindow.setCentralWidget(self.centralwidget)

        self.menubar = QtWidgets.QMenuBar(MainWindow)
        # self.menubar.setGeometry(QtCore.QRect(0, 0, 1850, 26))
        self.menubar.setObjectName("menubar")

        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)

        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.modeLabel = QLabel("MODE")
        self.listCountLabel = QLabel("LIST COUNT")
        self.statusbar.addWidget(self.listCountLabel)
        self.statusbar.addPermanentWidget(self.modeLabel)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        # File action
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setIcon(icon1)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave_Folder = QtWidgets.QAction(MainWindow)
        self.actionSave_Folder.setIcon(icon1)
        self.actionSave_Folder.setObjectName("actionSave_Folder")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(
            QtGui.QPixmap("labelvim/icon/quit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off
        )
        self.actionQuit.setIcon(icon15)
        self.actionQuit.setObjectName("actionQuit")
        self.actionNext = QtWidgets.QAction(MainWindow)
        self.actionNext.setObjectName("actionNext")
        self.actionPrevious = QtWidgets.QAction(MainWindow)
        self.actionPrevious.setObjectName("actionPrevious")
        self.actionExport = QtWidgets.QAction(MainWindow)
        self.actionExport.setObjectName("actionExport")
        self.actionSave_Mask = QtWidgets.QAction(MainWindow)
        self.actionSave_Mask.setCheckable(True)
        icon17 = QtGui.QIcon()
        icon17.addPixmap(
            QtGui.QPixmap("labelvim/icon/yes.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off
        )
        self.actionSave_Mask.setIcon(icon17)
        self.actionSave_Mask.setObjectName("actionSave_Mask")
        self.actionSave_Mask.setIconVisibleInMenu(False)
        self.actionSave_Mask_include_img = QtWidgets.QAction(MainWindow)
        self.actionSave_Mask_include_img.setCheckable(True)
        icon17 = QtGui.QIcon()
        icon17.addPixmap(
            QtGui.QPixmap("labelvim/icon/yes.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off
        )
        self.actionSave_Mask_include_img.setIcon(icon17)
        self.actionSave_Mask_include_img.setObjectName("actionSave_Mask_include_img")
        self.actionSave_Mask_include_img.setIconVisibleInMenu(False)
        self.actionDelete_File = QtWidgets.QAction(MainWindow)
        self.actionDelete_File.setIcon(icon4)
        self.actionDelete_File.setObjectName("actionDelete_File")

        # Edit action
        self.actionAnnotation_Type = QtWidgets.QAction(MainWindow)
        self.actionAnnotation_Type.setObjectName("actionAnnotation_Type")
        self.actionAnnotation_Type.setCheckable(False)
        annotation_type_con = QtGui.QIcon()
        annotation_type_con.addPixmap(
            QtGui.QPixmap("labelvim/icon/objects.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off
        )
        self.actionAnnotation_Type.setIcon(annotation_type_con)

        # view action
        self.actionFill = QtWidgets.QAction(MainWindow)
        self.actionFill.setCheckable(True)
        icon25 = QtGui.QIcon()
        icon25.addPixmap(
            QtGui.QPixmap("labelvim/icon/color.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off
        )
        self.actionFill.setIcon(icon25)
        self.actionFill.setObjectName("actionFill")
        self.actionZoom_In = QtWidgets.QAction(MainWindow)
        self.actionZoom_In.setIcon(icon9)
        self.actionZoom_In.setObjectName("actionZoom_In")
        self.actionZoom_Out = QtWidgets.QAction(MainWindow)
        self.actionZoom_Out.setIcon(icon10)
        self.actionZoom_Out.setObjectName("actionZoom_Out")
        self.actionFit_Windows = QtWidgets.QAction(MainWindow)
        self.actionFit_Windows.setIcon(icon11)
        self.actionFit_Windows.setObjectName("actionFit_Windows")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setCheckable(False)
        self.actionSave.setIcon(icon12)
        self.actionSave.setObjectName("actionSave")
        self.actionLine_Color = QtWidgets.QAction(MainWindow)
        icon26 = QtGui.QIcon()
        icon26.addPixmap(
            QtGui.QPixmap("labelvim/icon/color-line.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off
        )
        self.actionLine_Color.setIcon(icon26)
        self.actionLine_Color.setObjectName("actionLine_Color")

        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave_Folder)
        self.menuFile.addAction(self.actionNext)
        self.menuFile.addAction(self.actionPrevious)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionExport)
        self.menuFile.addAction(self.actionSave_Mask)
        self.menuFile.addAction(self.actionSave_Mask_include_img)
        self.menuFile.addAction(self.actionDelete_File)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)

        self.menuEdit.addAction(self.actionAnnotation_Type)

        self.menuView.addAction(self.actionFill)
        self.menuView.addAction(self.actionZoom_In)
        self.menuView.addAction(self.actionZoom_Out)
        self.menuView.addAction(self.actionFit_Windows)
        self.menuView.addAction(self.actionLine_Color)

        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "LabelVim"))
        MainWindow.setToolTip(_translate("MainWindow", "LabelVim"))
        self.SaveDirBtn.setToolTip(_translate("MainWindow", "Save Directory"))
        self.NextBtn.setToolTip(_translate("MainWindow", "Next Image"))
        self.PreviousBtn.setToolTip(_translate("MainWindow", "Previous Image"))
        self.DeleteFileBtn.setToolTip(
            _translate("MainWindow", "Delete file from file list")
        )
        self.OpenDirBtn.setToolTip(_translate("MainWindow", "Load data from Folder"))
        self.CreateObjectBtn.setToolTip(_translate("MainWindow", "Create"))
        self.EditObjectBtn.setToolTip(_translate("MainWindow", "Edit"))
        self.DeleteAnnotationBtn.setToolTip(
            _translate("MainWindow", "Delete selected annotation")
        )
        self.ClearAnnotationBtn.setToolTip(_translate("MainWindow", "Clear"))
        self.ZoomInBtn.setToolTip(_translate("MainWindow", "Zoom In"))
        self.ZoomOutBtn.setToolTip(_translate("MainWindow", "ZoomOutBtn"))
        self.ZoomFitBtn.setToolTip(_translate("MainWindow", "Fit Windows"))
        self.ZoomLabel.setToolTip(_translate("MainWindow", "Zoom"))
        self.SaveBtn.setToolTip(_translate("MainWindow", "Fit Windows"))
        self.labelLabels.setText(_translate("MainWindow", "Label"))
        self.labelObjectList.setText(_translate("MainWindow", "Object List"))
        self.labelFileList.setText(_translate("MainWindow", "File List"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuView.setTitle(_translate("MainWindow", "View"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.actionOpen.setText(_translate("MainWindow", "Open Folder"))
        self.actionOpen.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionSave_Folder.setText(_translate("MainWindow", "Save Folder"))
        self.actionSave_Folder.setShortcut(_translate("MainWindow", "Ctrl+U"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
        self.actionQuit.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.actionNext.setText(_translate("MainWindow", "Next"))
        self.actionNext.setShortcut(_translate("MainWindow", "Ctrl+A"))
        self.actionPrevious.setText(_translate("MainWindow", "Previous"))
        self.actionPrevious.setShortcut(_translate("MainWindow", "Ctrl+D"))
        self.actionSave_Mask.setText(_translate("MainWindow", "Save Mask"))
        self.actionSave_Mask_include_img.setText(
            _translate("MainWindow", "Save Mask with Image")
        )
        self.actionDelete_File.setText(_translate("MainWindow", "Delete File"))
        self.actionDelete_File.setShortcut(_translate("MainWindow", "Ctrl+Del"))
        self.actionFit_Windows.setText(_translate("MainWindow", "Fit Windows"))
        self.actionFit_Windows.setShortcut(_translate("MainWindow", "Ctrl+0"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionExport.setText(_translate("MainWindow", "Export"))
        self.actionSave.setShortcut(_translate("MainWindow", "Ctrl+S"))

        self.actionAnnotation_Type.setText(_translate("MainWindow", "Annotation Type"))
        self.actionFill.setText(_translate("MainWindow", "Polygon Fill"))
        self.actionZoom_In.setText(_translate("MainWindow", "Zoom In"))
        self.actionZoom_In.setShortcut(_translate("MainWindow", "Ctrl+="))
        self.actionZoom_Out.setText(_translate("MainWindow", "Zoom Out"))
        self.actionZoom_Out.setShortcut(_translate("MainWindow", "Ctrl+-"))
        self.actionLine_Color.setText(_translate("MainWindow", "Line Color"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
